runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: public

- url: /(.*\.pdf)
  secure: always
  redirect_http_response_code: 301
  mime_type: application/pdf
  static_files: static/\1
  upload: static/(.*\.pdf)
